describe("create account page", () => {
    const user = cy
    it("should display validation errors", () => {
        user.visit("/")
        user.findByText(/create an account/i).click()
        user.url().should("include", "/create-account")
        user.findByPlaceholderText(/email/i).type("test")
        user.findByRole("alert").should("have.text", "Please enter a valid email")
        user.findByPlaceholderText(/email/i).clear()
        user.findByRole("alert").should("have.text", "Email is required")
        user.findByPlaceholderText(/email/i).type("test@test.com")
        user.findByPlaceholderText(/password/i).type("testtest").clear()
        user.findByRole("alert").should("have.text", "Password is required")
        user.findByPlaceholderText(/password/i).type("test")
        user.findByRole("alert").should("have.text", "Password must be at least 5 characters")
        user.findByPlaceholderText(/email/i).clear().type("cypress@cypress.com")
        user.findByPlaceholderText(/password/i).clear().type("cypress")
        user.findByRole("select").select("Client")
        user.findByRole("button").should("not.have.class", "pointer-events-none").click()
        user.findByRole("alert").should("exist")
        //check backend validation errors
    })
    it("should render the create account page", () => {
        user.visit("/create-account")
        user.findByPlaceholderText(/email/i).type("cypress@cypress.com")
        user.findByPlaceholderText(/password/i).type("cypress")
        user.findByRole("select").select("Client")
        // user.findByRole("button").should("not.have.class", "pointer-events-none").click()
        // check that user can login again
        // user.findByPlaceholderText(/email/i).type("cypress@cypress.com")
        // user.findByPlaceholderText(/password/i).type("cypress")
        // user.findByRole("button").should("not.have.class", "pointer-events-none").click()
        // user.window().its("localStorage.super-eats-token").should("be.a","string")
    })
})